### ISSUE TITLE
Persistent Login Error After Entering Incorrect Information

### ISSUE THREAD

**Issue by heesookiim** [norandomtechie/queup#1]
While logging in, I mistakenly entered incorrect information. 

Afterwards, I get the following error message in the website whenever I try to access https://engineering.purdue.edu/~menon18/queup//
`Please log in with your username, not your email.  You may need to clear site settings and try again.`

I have already cleared my Safari cache, but the error message persists. What steps should I take to resolve this issue?

![Screenshot 2024-01-17 at 10 18 31 PM](https://github.com/norandomtechie/queup/assets/107389219/d9ae926f-96c2-4eba-9f90-d19105f5318c)

**Comment by norandomtechie** [comment]
Try this:

https://stackoverflow.com/a/6224994

**Comment by heesookiim** [comment]
Using Secret mode (cmd + shift + N) in Safari allows me to log in to the server!  However, this seems like just a temporary solution.

I've tried another method: https://any:any@example.com
but my password contain @ character so this doesn't also work. 

Would there be a complete solution to this for a Safari user?

**Comment by norandomtechie** [comment]
Is it in keychain access as this one seems to suggest?

https://apple.stackexchange.com/a/459913

You'll need to do a bit of Googling to figure this out.  Search for "clear basic auth password safari".

**Comment by heesookiim** [comment]
Changing the saved id and password in keychain access fixed the issue! Thank you so much :)
